### ISSUE TITLE
Swapping with last element

### ISSUE THREAD

**Issue by FrozenIce0617** [mimiton/vue-drag-sortable#1]
I am going to swap with last element, but it is not working.

**Comment by mimiton** [comment]
@FrozenIce0617 I'm sorry, it's a known bug. But I don't have time to fix it these days, maybe some weeks later.

**Comment by mimiton** [comment]
@FrozenIce0617 I published v0.2.1 just now, fixed that bug and made some imprevements.You may have try.Thx.^_^

**Comment by FrozenIce0617** [comment]
Thanks, @mimiton
